/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ui;

import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import model.databaseConnection;


/**
 *
 * @author shrey
 */
public class createHospitalJPanel extends javax.swing.JPanel {

    /**
     * Creates new form createHospital
     */
    databaseConnection databaseConnection;
    
    public createHospitalJPanel(databaseConnection databaseConnection) {
        initComponents();
        this.databaseConnection = databaseConnection;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblHospitalName = new javax.swing.JLabel();
        lblHospitalZipcode = new javax.swing.JLabel();
        txtHospitalName = new javax.swing.JTextField();
        txtHospitalZipcode = new javax.swing.JTextField();
        hospitalAdminSubmitButton = new javax.swing.JButton();
        lblCreateCommunity = new javax.swing.JLabel();
        lblCityName = new javax.swing.JLabel();
        lblCommunityName = new javax.swing.JLabel();
        txtCityName = new javax.swing.JTextField();
        txtCommunityName = new javax.swing.JTextField();

        setBackground(new java.awt.Color(0, 255, 255));

        lblHospitalName.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        lblHospitalName.setText("Pet Hospital Name :");

        lblHospitalZipcode.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        lblHospitalZipcode.setText("Hospital Zipcode :");

        txtHospitalName.setPreferredSize(new java.awt.Dimension(71, 30));

        txtHospitalZipcode.setPreferredSize(new java.awt.Dimension(71, 30));
        txtHospitalZipcode.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtHospitalZipcodeActionPerformed(evt);
            }
        });

        hospitalAdminSubmitButton.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        hospitalAdminSubmitButton.setForeground(new java.awt.Color(255, 51, 51));
        hospitalAdminSubmitButton.setText("Submit");
        hospitalAdminSubmitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hospitalAdminSubmitButtonActionPerformed(evt);
            }
        });

        lblCreateCommunity.setBackground(new java.awt.Color(255, 255, 255));
        lblCreateCommunity.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblCreateCommunity.setForeground(new java.awt.Color(255, 0, 0));
        lblCreateCommunity.setText("                                                                         Create Hospital");

        lblCityName.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        lblCityName.setText("City Name :");

        lblCommunityName.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        lblCommunityName.setText("Community Name :");

        txtCityName.setPreferredSize(new java.awt.Dimension(71, 30));

        txtCommunityName.setPreferredSize(new java.awt.Dimension(71, 30));
        txtCommunityName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCommunityNameActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblCreateCommunity, javax.swing.GroupLayout.PREFERRED_SIZE, 896, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(205, 205, 205)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(lblHospitalZipcode)
                                    .addComponent(lblHospitalName))
                                .addGap(114, 114, 114)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtHospitalName, javax.swing.GroupLayout.PREFERRED_SIZE, 218, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtHospitalZipcode, javax.swing.GroupLayout.PREFERRED_SIZE, 218, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addGap(128, 128, 128)
                                    .addComponent(hospitalAdminSubmitButton, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(lblCityName, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(lblCommunityName))
                                    .addGap(114, 114, 114)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(txtCityName, javax.swing.GroupLayout.PREFERRED_SIZE, 218, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(txtCommunityName, javax.swing.GroupLayout.PREFERRED_SIZE, 218, javax.swing.GroupLayout.PREFERRED_SIZE)))))))
                .addContainerGap(160, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblCreateCommunity, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(101, 101, 101)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCityName, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtCityName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCommunityName, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtCommunityName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblHospitalName, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtHospitalName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblHospitalZipcode, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtHospitalZipcode, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(49, 49, 49)
                .addComponent(hospitalAdminSubmitButton, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(109, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void txtHospitalZipcodeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtHospitalZipcodeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtHospitalZipcodeActionPerformed

    private void hospitalAdminSubmitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hospitalAdminSubmitButtonActionPerformed
        try {
            // TODO add your handling code here:
            String cityName = txtCityName.getText();
            String communityName = txtCommunityName.getText();
            String hospitalName = txtHospitalName.getText();
            String hospitalZipCode = txtHospitalZipcode.getText();
            databaseConnection.insertHospitals(cityName, communityName, hospitalName, hospitalZipCode);
            JOptionPane.showMessageDialog(this, "Hospital Created Successfully!");
            txtCityName.setText("");
            txtCommunityName.setText("");
            txtHospitalName.setText("");
            txtHospitalZipcode.setText("");
            
        } catch (Exception ex) {
            Logger.getLogger(createHospitalJPanel.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        
    }//GEN-LAST:event_hospitalAdminSubmitButtonActionPerformed

    private void txtCommunityNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCommunityNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCommunityNameActionPerformed
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton hospitalAdminSubmitButton;
    private javax.swing.JLabel lblCityName;
    private javax.swing.JLabel lblCommunityName;
    private javax.swing.JLabel lblCreateCommunity;
    private javax.swing.JLabel lblHospitalName;
    private javax.swing.JLabel lblHospitalZipcode;
    private javax.swing.JTextField txtCityName;
    private javax.swing.JTextField txtCommunityName;
    private javax.swing.JTextField txtHospitalName;
    private javax.swing.JTextField txtHospitalZipcode;
    // End of variables declaration//GEN-END:variables
}
