/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ui;

import java.sql.ResultSet;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import model.databaseConnection;


/**
 *
 * @author shrey
 */
public class createDoctorJPanel extends javax.swing.JPanel {

    /**
     * Creates new form createHospital
     */
    databaseConnection databaseConnection;
    
    public createDoctorJPanel(databaseConnection databaseConnection) {
        initComponents();
        this.databaseConnection = databaseConnection;
        populateHospitalComboBox();
    }
    
    private void populateHospitalComboBox()
    {
        try {
            ResultSet result = databaseConnection.executeSelect("SELECT * FROM hospitals");
            
            while(result.next())
            {
                selectHospitalCombo.addItem(result.getString("hospital_name"));
            }
        } catch (Exception ex) {
            Logger.getLogger(createDoctorJPanel.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblContactNumber = new javax.swing.JLabel();
        lblEmailID = new javax.swing.JLabel();
        txtContactNumber = new javax.swing.JTextField();
        txtEmailID = new javax.swing.JTextField();
        hospitalAdminSubmitButton = new javax.swing.JButton();
        lblCreateCommunity = new javax.swing.JLabel();
        lblFirstName = new javax.swing.JLabel();
        lblLastName = new javax.swing.JLabel();
        txtFirstName = new javax.swing.JTextField();
        txtLastName = new javax.swing.JTextField();
        selectHospitalComboBox = new javax.swing.JLabel();
        selectHospitalCombo = new javax.swing.JComboBox<>();
        lblDoctorUserName = new javax.swing.JLabel();
        txtDoctorUserName = new javax.swing.JTextField();
        lblDoctorPassword = new javax.swing.JLabel();
        txtDoctorPassword = new javax.swing.JPasswordField();

        setBackground(new java.awt.Color(0, 255, 255));

        lblContactNumber.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        lblContactNumber.setText("Contact Number :");

        lblEmailID.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        lblEmailID.setText("Email ID :");

        txtContactNumber.setPreferredSize(new java.awt.Dimension(71, 30));

        txtEmailID.setPreferredSize(new java.awt.Dimension(71, 30));
        txtEmailID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtEmailIDActionPerformed(evt);
            }
        });

        hospitalAdminSubmitButton.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        hospitalAdminSubmitButton.setForeground(new java.awt.Color(255, 51, 51));
        hospitalAdminSubmitButton.setText("Create Doctor");
        hospitalAdminSubmitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hospitalAdminSubmitButtonActionPerformed(evt);
            }
        });

        lblCreateCommunity.setBackground(new java.awt.Color(255, 255, 255));
        lblCreateCommunity.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblCreateCommunity.setForeground(new java.awt.Color(255, 0, 0));
        lblCreateCommunity.setText("                                                                         Create Doctor");

        lblFirstName.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        lblFirstName.setText("First Name :");

        lblLastName.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        lblLastName.setText("Last Name :");

        txtFirstName.setPreferredSize(new java.awt.Dimension(71, 30));

        txtLastName.setPreferredSize(new java.awt.Dimension(71, 30));
        txtLastName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtLastNameActionPerformed(evt);
            }
        });

        selectHospitalComboBox.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        selectHospitalComboBox.setText(" Select Hospital :");

        selectHospitalCombo.setPreferredSize(new java.awt.Dimension(72, 30));
        selectHospitalCombo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                selectHospitalComboActionPerformed(evt);
            }
        });

        lblDoctorUserName.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        lblDoctorUserName.setText("User Name :");

        txtDoctorUserName.setPreferredSize(new java.awt.Dimension(71, 30));
        txtDoctorUserName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDoctorUserNameActionPerformed(evt);
            }
        });

        lblDoctorPassword.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        lblDoctorPassword.setText("Password :");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblCreateCommunity, javax.swing.GroupLayout.PREFERRED_SIZE, 896, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(233, 233, 233)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblLastName)
                                .addGap(114, 114, 114)
                                .addComponent(txtLastName, javax.swing.GroupLayout.PREFERRED_SIZE, 218, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblFirstName)
                                .addGap(114, 114, 114)
                                .addComponent(txtFirstName, javax.swing.GroupLayout.PREFERRED_SIZE, 218, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(347, 347, 347)
                        .addComponent(hospitalAdminSubmitButton))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblDoctorUserName)
                                .addGap(114, 114, 114)
                                .addComponent(txtDoctorUserName, javax.swing.GroupLayout.PREFERRED_SIZE, 218, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblEmailID)
                                .addGap(114, 114, 114)
                                .addComponent(txtEmailID, javax.swing.GroupLayout.PREFERRED_SIZE, 218, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblContactNumber)
                                .addGap(114, 114, 114)
                                .addComponent(txtContactNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 218, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(selectHospitalComboBox)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(36, 36, 36)
                                        .addComponent(lblDoctorPassword)))
                                .addGap(114, 114, 114)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(selectHospitalCombo, javax.swing.GroupLayout.PREFERRED_SIZE, 218, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtDoctorPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 218, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(265, 265, 265)))
                .addContainerGap(160, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblCreateCommunity, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblFirstName, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtFirstName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblLastName, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtLastName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblContactNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtContactNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblEmailID, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtEmailID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblDoctorUserName, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtDoctorUserName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblDoctorPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtDoctorPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(selectHospitalCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(selectHospitalComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(42, 42, 42)
                .addComponent(hospitalAdminSubmitButton, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(85, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void txtEmailIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEmailIDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtEmailIDActionPerformed

    private void hospitalAdminSubmitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hospitalAdminSubmitButtonActionPerformed
        
        try {
            String first_name = txtFirstName.getText();
            String last_name = txtLastName.getText();
            String email_ID = txtEmailID.getText();
            String contact_number = "+1" + txtContactNumber.getText();
            String username = txtDoctorUserName.getText();
            String password = txtDoctorPassword.getText();
            String hospital_name = selectHospitalCombo.getSelectedItem().toString();
            
            databaseConnection.insertDoctors(first_name, last_name, email_ID, contact_number, hospital_name, username, password);
            JOptionPane.showMessageDialog(this, "Doctor Created Successfully!");
            txtFirstName.setText("");
            txtLastName.setText("");
            txtEmailID.setText("");
            txtContactNumber.setText("");
            txtDoctorUserName.setText("");
            txtDoctorPassword.setText("");
        } catch (Exception ex) {
            Logger.getLogger(createDoctorJPanel.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_hospitalAdminSubmitButtonActionPerformed

    private void txtLastNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtLastNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtLastNameActionPerformed

    private void selectHospitalComboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_selectHospitalComboActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_selectHospitalComboActionPerformed

    private void txtDoctorUserNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDoctorUserNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDoctorUserNameActionPerformed
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton hospitalAdminSubmitButton;
    private javax.swing.JLabel lblContactNumber;
    private javax.swing.JLabel lblCreateCommunity;
    private javax.swing.JLabel lblDoctorPassword;
    private javax.swing.JLabel lblDoctorUserName;
    private javax.swing.JLabel lblEmailID;
    private javax.swing.JLabel lblFirstName;
    private javax.swing.JLabel lblLastName;
    private javax.swing.JComboBox<String> selectCommunityCombo;
    private javax.swing.JComboBox<String> selectCommunityCombo1;
    private javax.swing.JComboBox<String> selectCommunityCombo2;
    private javax.swing.JComboBox<String> selectCommunityCombo3;
    private javax.swing.JComboBox<String> selectHospitalCombo;
    private javax.swing.JLabel selectHospitalComboBox;
    private javax.swing.JTextField txtContactNumber;
    private javax.swing.JPasswordField txtDoctorPassword;
    private javax.swing.JTextField txtDoctorUserName;
    private javax.swing.JTextField txtEmailID;
    private javax.swing.JTextField txtFirstName;
    private javax.swing.JTextField txtLastName;
    // End of variables declaration//GEN-END:variables
}
