/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ui;
import java.sql.ResultSet;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import model.databaseConnection;

/**
 *
 * @author shrey
 */
public class kennelAdminUpdatePrice extends javax.swing.JPanel {

    /**
     * Creates new form petFoodAdminUpdatePrice
     */
    databaseConnection databaseConnection;
    
    public kennelAdminUpdatePrice(databaseConnection databaseConnection) {
        initComponents();
        this.databaseConnection = databaseConnection;
        txtKennelName.setEditable(false);
        populateTable();
    }
    
    private void populateTable()
    {
        try {
            ResultSet result = databaseConnection.executeSelect("SELECT * FROM kennel");
            DefaultTableModel model = (DefaultTableModel) tblKennel.getModel();
            model.setRowCount(0);
            while(result.next())
            {
                Object[] row = new Object[4];
                row[0] = result.getInt("id");
                row[1] = result.getString("kennel_name");
                row[2] = result.getString("kennel_address");
                row[3] = result.getInt("price_per_day");
                model.addRow(row);
            }
        } catch (Exception ex) {
            Logger.getLogger(kennelAdminUpdatePrice.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        tblKennel = new javax.swing.JTable();
        lblUpdateAccessoryPrice = new javax.swing.JLabel();
        lblKennelName = new javax.swing.JLabel();
        txtKennelName = new javax.swing.JTextField();
        lblKennelPrice = new javax.swing.JLabel();
        txtKennelPrice = new javax.swing.JTextField();
        btnUpdatePrice = new javax.swing.JButton();

        setBackground(new java.awt.Color(0, 255, 255));

        tblKennel.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Kennel", "Kennel Name", "Kennel Address", "Kennel Price Per Day"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class
            };
            boolean[] canEdit = new boolean [] {
                true, true, true, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblKennel.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        tblKennel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblKennelMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tblKennel);

        lblUpdateAccessoryPrice.setBackground(new java.awt.Color(255, 255, 255));
        lblUpdateAccessoryPrice.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        lblUpdateAccessoryPrice.setForeground(new java.awt.Color(255, 0, 0));
        lblUpdateAccessoryPrice.setText("                                                                  Select a Kennel to Update Price Per Day");

        lblKennelName.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        lblKennelName.setText("Kennel Name :");

        txtKennelName.setPreferredSize(new java.awt.Dimension(71, 30));
        txtKennelName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtKennelNameActionPerformed(evt);
            }
        });

        lblKennelPrice.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        lblKennelPrice.setText("Kennel Price Per Day :");

        txtKennelPrice.setPreferredSize(new java.awt.Dimension(71, 30));
        txtKennelPrice.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtKennelPriceActionPerformed(evt);
            }
        });

        btnUpdatePrice.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        btnUpdatePrice.setForeground(new java.awt.Color(255, 0, 0));
        btnUpdatePrice.setText("Update Price");
        btnUpdatePrice.setPreferredSize(new java.awt.Dimension(76, 30));
        btnUpdatePrice.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdatePriceActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblUpdateAccessoryPrice, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 811, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(27, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblKennelName, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(29, 29, 29))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblKennelPrice)
                                .addGap(44, 44, 44)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtKennelName, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 218, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtKennelPrice, javax.swing.GroupLayout.PREFERRED_SIZE, 218, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(246, 246, 246))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(btnUpdatePrice, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(309, 309, 309))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(9, 9, 9)
                .addComponent(lblUpdateAccessoryPrice, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(89, 89, 89)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtKennelName, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblKennelName, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtKennelPrice, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblKennelPrice, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(74, 74, 74)
                .addComponent(btnUpdatePrice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(97, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void txtKennelNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtKennelNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtKennelNameActionPerformed

    private void txtKennelPriceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtKennelPriceActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtKennelPriceActionPerformed

    private void btnUpdatePriceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdatePriceActionPerformed
        try {
            // TODO add your handling code here:
            DefaultTableModel model = (DefaultTableModel) tblKennel.getModel();
            int selectedRowIndex = tblKennel.getSelectedRow();
            int kennelID = (int) model.getValueAt(selectedRowIndex, 0);
            int newPrice = Integer.parseInt(txtKennelPrice.getText());
            
            databaseConnection.executeKennelPriceUpdate("UPDATE kennel SET price_per_day = ? WHERE id = ?", newPrice, kennelID);
   
            JOptionPane.showMessageDialog(this, "Price Updated Successfully!");
            txtKennelName.setText("");
            txtKennelPrice.setText("");
            populateTable();
        } catch (Exception ex) {
            Logger.getLogger(kennelAdminUpdatePrice.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }//GEN-LAST:event_btnUpdatePriceActionPerformed

    private void tblKennelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblKennelMouseClicked
        // TODO add your handling code here:
        DefaultTableModel model = (DefaultTableModel) tblKennel.getModel();
        int selectedRowIndex = tblKennel.getSelectedRow();
        String kennelName = (String) model.getValueAt(selectedRowIndex, 1);
        txtKennelName.setText(kennelName);
    }//GEN-LAST:event_tblKennelMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnUpdatePrice;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblKennelName;
    private javax.swing.JLabel lblKennelPrice;
    private javax.swing.JLabel lblUpdateAccessoryPrice;
    private javax.swing.JTable tblKennel;
    private javax.swing.JTextField txtKennelName;
    private javax.swing.JTextField txtKennelPrice;
    // End of variables declaration//GEN-END:variables
}
