/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ui;

import model.databaseConnection;

/**
 *
 * @author shrey
 */
public class petFoodAdmin extends javax.swing.JPanel {

    /**
     * Creates new form petFoodAdmin
     */
    databaseConnection databaseConnection;
    
    public petFoodAdmin(databaseConnection databaseConnection) {
        initComponents();
        this.databaseConnection = databaseConnection;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        petFoodAdminSplitPane = new javax.swing.JSplitPane();
        petFoodAdminControlArea = new javax.swing.JPanel();
        btnUpdatePrice = new javax.swing.JButton();
        btnOrderProduct = new javax.swing.JButton();
        petFoodAdminWorkArea = new javax.swing.JPanel();
        lblFoodStoreAdmin = new javax.swing.JLabel();

        petFoodAdminSplitPane.setDividerLocation(120);

        petFoodAdminControlArea.setBackground(new java.awt.Color(102, 255, 102));

        btnUpdatePrice.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        btnUpdatePrice.setForeground(new java.awt.Color(255, 0, 0));
        btnUpdatePrice.setText("Update Price");
        btnUpdatePrice.setPreferredSize(new java.awt.Dimension(76, 30));
        btnUpdatePrice.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdatePriceActionPerformed(evt);
            }
        });

        btnOrderProduct.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        btnOrderProduct.setForeground(new java.awt.Color(255, 0, 0));
        btnOrderProduct.setText("Order Product");
        btnOrderProduct.setPreferredSize(new java.awt.Dimension(76, 30));
        btnOrderProduct.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOrderProductActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout petFoodAdminControlAreaLayout = new javax.swing.GroupLayout(petFoodAdminControlArea);
        petFoodAdminControlArea.setLayout(petFoodAdminControlAreaLayout);
        petFoodAdminControlAreaLayout.setHorizontalGroup(
            petFoodAdminControlAreaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(petFoodAdminControlAreaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnUpdatePrice, javax.swing.GroupLayout.DEFAULT_SIZE, 112, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(petFoodAdminControlAreaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(petFoodAdminControlAreaLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(btnOrderProduct, javax.swing.GroupLayout.DEFAULT_SIZE, 112, Short.MAX_VALUE)
                    .addContainerGap()))
        );
        petFoodAdminControlAreaLayout.setVerticalGroup(
            petFoodAdminControlAreaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(petFoodAdminControlAreaLayout.createSequentialGroup()
                .addGap(203, 203, 203)
                .addComponent(btnUpdatePrice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(391, Short.MAX_VALUE))
            .addGroup(petFoodAdminControlAreaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, petFoodAdminControlAreaLayout.createSequentialGroup()
                    .addContainerGap(305, Short.MAX_VALUE)
                    .addComponent(btnOrderProduct, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(289, 289, 289)))
        );

        petFoodAdminSplitPane.setLeftComponent(petFoodAdminControlArea);

        petFoodAdminWorkArea.setBackground(new java.awt.Color(0, 255, 255));

        lblFoodStoreAdmin.setBackground(new java.awt.Color(255, 255, 255));
        lblFoodStoreAdmin.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblFoodStoreAdmin.setForeground(new java.awt.Color(255, 0, 0));
        lblFoodStoreAdmin.setText("                                                                           Food Store Admin");

        javax.swing.GroupLayout petFoodAdminWorkAreaLayout = new javax.swing.GroupLayout(petFoodAdminWorkArea);
        petFoodAdminWorkArea.setLayout(petFoodAdminWorkAreaLayout);
        petFoodAdminWorkAreaLayout.setHorizontalGroup(
            petFoodAdminWorkAreaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(petFoodAdminWorkAreaLayout.createSequentialGroup()
                .addComponent(lblFoodStoreAdmin, javax.swing.GroupLayout.DEFAULT_SIZE, 849, Short.MAX_VALUE)
                .addContainerGap())
        );
        petFoodAdminWorkAreaLayout.setVerticalGroup(
            petFoodAdminWorkAreaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(petFoodAdminWorkAreaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblFoodStoreAdmin)
                .addContainerGap(593, Short.MAX_VALUE))
        );

        petFoodAdminSplitPane.setRightComponent(petFoodAdminWorkArea);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(petFoodAdminSplitPane)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(petFoodAdminSplitPane)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnUpdatePriceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdatePriceActionPerformed
        // TODO add your handling code here:
        petFoodAdminUpdatePrice petFoodUpdatePrice = new petFoodAdminUpdatePrice(databaseConnection);
        petFoodAdminSplitPane.setRightComponent(petFoodUpdatePrice);
    }//GEN-LAST:event_btnUpdatePriceActionPerformed

    private void btnOrderProductActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOrderProductActionPerformed
        // TODO add your handling code here:
        petFoodAdminOrderProductQuantity petFoodAdminOrderProductQuantity = new petFoodAdminOrderProductQuantity(databaseConnection);
        petFoodAdminSplitPane.setRightComponent(petFoodAdminOrderProductQuantity);
    }//GEN-LAST:event_btnOrderProductActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnOrderProduct;
    private javax.swing.JButton btnUpdatePrice;
    private javax.swing.JLabel lblFoodStoreAdmin;
    private javax.swing.JPanel petFoodAdminControlArea;
    private javax.swing.JSplitPane petFoodAdminSplitPane;
    private javax.swing.JPanel petFoodAdminWorkArea;
    // End of variables declaration//GEN-END:variables
}
