/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ui;

import model.databaseConnection;

/**
 *
 * @author shrey
 */
public class petGroomingServiceAdmin extends javax.swing.JPanel {

    /**
     * Creates new form petFoodAdmin
     */
    databaseConnection databaseConnection;
    
    public petGroomingServiceAdmin(databaseConnection databaseConnection) {
        initComponents();
        this.databaseConnection = databaseConnection;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        petGroomingServiceAdminSplitPane = new javax.swing.JSplitPane();
        petGroomingServiceAdminControlArea = new javax.swing.JPanel();
        btnUpdatePrice = new javax.swing.JButton();
        btnCreateService = new javax.swing.JButton();
        petGroomingServiceAdminWorkArea = new javax.swing.JPanel();
        lblGroomingServiceAdmin = new javax.swing.JLabel();

        petGroomingServiceAdminSplitPane.setDividerLocation(130);

        petGroomingServiceAdminControlArea.setBackground(new java.awt.Color(102, 255, 102));

        btnUpdatePrice.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        btnUpdatePrice.setForeground(new java.awt.Color(255, 0, 0));
        btnUpdatePrice.setText("Update Price");
        btnUpdatePrice.setPreferredSize(new java.awt.Dimension(76, 30));
        btnUpdatePrice.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdatePriceActionPerformed(evt);
            }
        });

        btnCreateService.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        btnCreateService.setForeground(new java.awt.Color(255, 0, 0));
        btnCreateService.setText("Create Service");
        btnCreateService.setPreferredSize(new java.awt.Dimension(76, 30));
        btnCreateService.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCreateServiceActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout petGroomingServiceAdminControlAreaLayout = new javax.swing.GroupLayout(petGroomingServiceAdminControlArea);
        petGroomingServiceAdminControlArea.setLayout(petGroomingServiceAdminControlAreaLayout);
        petGroomingServiceAdminControlAreaLayout.setHorizontalGroup(
            petGroomingServiceAdminControlAreaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(petGroomingServiceAdminControlAreaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnUpdatePrice, javax.swing.GroupLayout.DEFAULT_SIZE, 118, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(petGroomingServiceAdminControlAreaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(petGroomingServiceAdminControlAreaLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(btnCreateService, javax.swing.GroupLayout.DEFAULT_SIZE, 118, Short.MAX_VALUE)
                    .addContainerGap()))
        );
        petGroomingServiceAdminControlAreaLayout.setVerticalGroup(
            petGroomingServiceAdminControlAreaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(petGroomingServiceAdminControlAreaLayout.createSequentialGroup()
                .addGap(203, 203, 203)
                .addComponent(btnUpdatePrice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(391, Short.MAX_VALUE))
            .addGroup(petGroomingServiceAdminControlAreaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, petGroomingServiceAdminControlAreaLayout.createSequentialGroup()
                    .addContainerGap(305, Short.MAX_VALUE)
                    .addComponent(btnCreateService, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(289, 289, 289)))
        );

        petGroomingServiceAdminSplitPane.setLeftComponent(petGroomingServiceAdminControlArea);

        petGroomingServiceAdminWorkArea.setBackground(new java.awt.Color(0, 255, 255));

        lblGroomingServiceAdmin.setBackground(new java.awt.Color(255, 255, 255));
        lblGroomingServiceAdmin.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblGroomingServiceAdmin.setForeground(new java.awt.Color(255, 0, 0));
        lblGroomingServiceAdmin.setText("                                                                         Grooming Service Admin");

        javax.swing.GroupLayout petGroomingServiceAdminWorkAreaLayout = new javax.swing.GroupLayout(petGroomingServiceAdminWorkArea);
        petGroomingServiceAdminWorkArea.setLayout(petGroomingServiceAdminWorkAreaLayout);
        petGroomingServiceAdminWorkAreaLayout.setHorizontalGroup(
            petGroomingServiceAdminWorkAreaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(petGroomingServiceAdminWorkAreaLayout.createSequentialGroup()
                .addComponent(lblGroomingServiceAdmin, javax.swing.GroupLayout.DEFAULT_SIZE, 843, Short.MAX_VALUE)
                .addContainerGap())
        );
        petGroomingServiceAdminWorkAreaLayout.setVerticalGroup(
            petGroomingServiceAdminWorkAreaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(petGroomingServiceAdminWorkAreaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblGroomingServiceAdmin)
                .addContainerGap(593, Short.MAX_VALUE))
        );

        petGroomingServiceAdminSplitPane.setRightComponent(petGroomingServiceAdminWorkArea);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(petGroomingServiceAdminSplitPane)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(petGroomingServiceAdminSplitPane)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnUpdatePriceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdatePriceActionPerformed
        // TODO add your handling code here:
        petGroomingServiceAdminUpdatePrice petGroomingUpdatePrice = new petGroomingServiceAdminUpdatePrice(databaseConnection);
        petGroomingServiceAdminSplitPane.setRightComponent(petGroomingUpdatePrice);
    }//GEN-LAST:event_btnUpdatePriceActionPerformed

    private void btnCreateServiceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCreateServiceActionPerformed
        // TODO add your handling code here:
        petGroomingServiceAdminCreateService petCreateGroomingService = new petGroomingServiceAdminCreateService(databaseConnection);
        petGroomingServiceAdminSplitPane.setRightComponent(petCreateGroomingService);
    }//GEN-LAST:event_btnCreateServiceActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCreateService;
    private javax.swing.JButton btnUpdatePrice;
    private javax.swing.JLabel lblGroomingServiceAdmin;
    private javax.swing.JPanel petGroomingServiceAdminControlArea;
    private javax.swing.JSplitPane petGroomingServiceAdminSplitPane;
    private javax.swing.JPanel petGroomingServiceAdminWorkArea;
    // End of variables declaration//GEN-END:variables
}
