/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ui;
import java.sql.ResultSet;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import model.databaseConnection;

/**
 *
 * @author shrey
 */
public class petGroomingServiceAdminCreateService extends javax.swing.JPanel {

    /**
     * Creates new form petFoodAdminUpdatePrice
     */
    databaseConnection databaseConnection;
    
    public petGroomingServiceAdminCreateService(databaseConnection databaseConnection) {
        initComponents();
        this.databaseConnection = databaseConnection;
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblUpdateFoodPrice = new javax.swing.JLabel();
        lblServiceName = new javax.swing.JLabel();
        txtServiceName = new javax.swing.JTextField();
        lblServiceTime = new javax.swing.JLabel();
        txtServiceTime = new javax.swing.JTextField();
        btnCreateService = new javax.swing.JButton();
        lblServiceCost = new javax.swing.JLabel();
        txtServiceCost = new javax.swing.JTextField();

        setBackground(new java.awt.Color(0, 255, 255));

        lblUpdateFoodPrice.setBackground(new java.awt.Color(255, 255, 255));
        lblUpdateFoodPrice.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        lblUpdateFoodPrice.setForeground(new java.awt.Color(255, 0, 0));
        lblUpdateFoodPrice.setText("                                                                    Create Grooming Service");

        lblServiceName.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        lblServiceName.setText("Service Name :");

        txtServiceName.setPreferredSize(new java.awt.Dimension(71, 30));
        txtServiceName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtServiceNameActionPerformed(evt);
            }
        });

        lblServiceTime.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        lblServiceTime.setText("Service Time :");

        txtServiceTime.setPreferredSize(new java.awt.Dimension(71, 30));
        txtServiceTime.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtServiceTimeActionPerformed(evt);
            }
        });

        btnCreateService.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        btnCreateService.setForeground(new java.awt.Color(255, 0, 0));
        btnCreateService.setText("Create Service");
        btnCreateService.setPreferredSize(new java.awt.Dimension(76, 30));
        btnCreateService.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCreateServiceActionPerformed(evt);
            }
        });

        lblServiceCost.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        lblServiceCost.setText("Service Cost :");

        txtServiceCost.setPreferredSize(new java.awt.Dimension(71, 30));
        txtServiceCost.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtServiceCostActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblUpdateFoodPrice, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(244, 244, 244)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblServiceCost, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblServiceTime, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtServiceCost, javax.swing.GroupLayout.PREFERRED_SIZE, 218, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtServiceTime, javax.swing.GroupLayout.PREFERRED_SIZE, 218, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(246, 246, 246))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblServiceName)
                        .addGap(87, 87, 87)
                        .addComponent(txtServiceName, javax.swing.GroupLayout.PREFERRED_SIZE, 218, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))))
            .addGroup(layout.createSequentialGroup()
                .addGap(373, 373, 373)
                .addComponent(btnCreateService, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(9, 9, 9)
                .addComponent(lblUpdateFoodPrice, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(109, 109, 109)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtServiceName, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblServiceName, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtServiceTime, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblServiceTime, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtServiceCost, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblServiceCost, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(82, 82, 82)
                .addComponent(btnCreateService, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(199, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void txtServiceNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtServiceNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtServiceNameActionPerformed

    private void txtServiceTimeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtServiceTimeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtServiceTimeActionPerformed

    private void btnCreateServiceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCreateServiceActionPerformed

        try {
            String serviceName = txtServiceName.getText();
            String serviceTime = txtServiceTime.getText();
            int serviceCost = Integer.parseInt(txtServiceCost.getText());
            databaseConnection.insertGroomingService(serviceName, serviceTime, serviceCost);
            JOptionPane.showMessageDialog(this, "Grooming Service Created Successfully!");
            txtServiceName.setText("");
            txtServiceTime.setText("");
            txtServiceCost.setText("");
        } catch (Exception ex) {
            Logger.getLogger(petGroomingServiceAdminCreateService.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnCreateServiceActionPerformed

    private void txtServiceCostActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtServiceCostActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtServiceCostActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCreateService;
    private javax.swing.JLabel lblServiceCost;
    private javax.swing.JLabel lblServiceName;
    private javax.swing.JLabel lblServiceTime;
    private javax.swing.JLabel lblUpdateFoodPrice;
    private javax.swing.JTextField txtServiceCost;
    private javax.swing.JTextField txtServiceName;
    private javax.swing.JTextField txtServiceTime;
    // End of variables declaration//GEN-END:variables
}
