/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ui;
import java.sql.ResultSet;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import model.databaseConnection;

/**
 *
 * @author shrey
 */
public class petGroomingServiceAdminUpdatePrice extends javax.swing.JPanel {

    /**
     * Creates new form petFoodAdminUpdatePrice
     */
    databaseConnection databaseConnection;
    
    public petGroomingServiceAdminUpdatePrice(databaseConnection databaseConnection) {
        initComponents();
        this.databaseConnection = databaseConnection;
        txtServiceName.setEditable(false);
        populateTable();
    }
    
    private void populateTable()
    {
        try {
            ResultSet result = databaseConnection.executeSelect("SELECT * FROM groomingservices");
            DefaultTableModel model = (DefaultTableModel) tablePetGroomingServices.getModel();
            model.setRowCount(0);
            while(result.next())
            {
                Object[] row = new Object[3];
                row[0] = result.getInt("id");
                row[1] = result.getString("service_name");
                row[2] = result.getInt("service_cost");
                model.addRow(row);
            }
        } catch (Exception ex) {
            Logger.getLogger(petGroomingServiceAdminUpdatePrice.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        tablePetGroomingServices = new javax.swing.JTable();
        lblUpdateFoodPrice = new javax.swing.JLabel();
        lblServiceName = new javax.swing.JLabel();
        txtServiceName = new javax.swing.JTextField();
        lblServiceNewPrice = new javax.swing.JLabel();
        txtServiceNewPrice = new javax.swing.JTextField();
        btnUpdateServicePrice = new javax.swing.JButton();

        setBackground(new java.awt.Color(0, 255, 255));

        tablePetGroomingServices.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Service Id", "Service Name", "Service Cost"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.Integer.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        tablePetGroomingServices.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        tablePetGroomingServices.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tablePetGroomingServicesMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tablePetGroomingServices);

        lblUpdateFoodPrice.setBackground(new java.awt.Color(255, 255, 255));
        lblUpdateFoodPrice.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        lblUpdateFoodPrice.setForeground(new java.awt.Color(255, 0, 0));
        lblUpdateFoodPrice.setText("                                                         Select a Grooming Service to Update Price");

        lblServiceName.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        lblServiceName.setText("Service Name :");

        txtServiceName.setPreferredSize(new java.awt.Dimension(71, 30));
        txtServiceName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtServiceNameActionPerformed(evt);
            }
        });

        lblServiceNewPrice.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        lblServiceNewPrice.setText("New Price :");

        txtServiceNewPrice.setPreferredSize(new java.awt.Dimension(71, 30));
        txtServiceNewPrice.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtServiceNewPriceActionPerformed(evt);
            }
        });

        btnUpdateServicePrice.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        btnUpdateServicePrice.setForeground(new java.awt.Color(255, 0, 0));
        btnUpdateServicePrice.setText("Update Price");
        btnUpdateServicePrice.setPreferredSize(new java.awt.Dimension(76, 30));
        btnUpdateServicePrice.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateServicePriceActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblUpdateFoodPrice, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 860, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane2)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblServiceNewPrice, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(29, 29, 29)
                                .addComponent(txtServiceNewPrice, javax.swing.GroupLayout.PREFERRED_SIZE, 218, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblServiceName, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(29, 29, 29)
                                .addComponent(txtServiceName, javax.swing.GroupLayout.PREFERRED_SIZE, 218, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(246, 246, 246))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnUpdateServicePrice, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(309, 309, 309))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(9, 9, 9)
                .addComponent(lblUpdateFoodPrice, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(96, 96, 96)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtServiceName, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblServiceName, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtServiceNewPrice, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblServiceNewPrice, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(74, 74, 74)
                .addComponent(btnUpdateServicePrice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(97, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void txtServiceNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtServiceNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtServiceNameActionPerformed

    private void txtServiceNewPriceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtServiceNewPriceActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtServiceNewPriceActionPerformed

    private void btnUpdateServicePriceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateServicePriceActionPerformed
        try {
            // TODO add your handling code here:
            DefaultTableModel model = (DefaultTableModel) tablePetGroomingServices.getModel();
            int selectedRowIndex = tablePetGroomingServices.getSelectedRow();
            int serviceID = (int) model.getValueAt(selectedRowIndex, 0);
            int newPrice = Integer.parseInt(txtServiceNewPrice.getText());
            
            databaseConnection.executeGroomingServicePriceUpdate("UPDATE groomingservices SET service_cost = ? WHERE id = ?", newPrice, serviceID);
   
            JOptionPane.showMessageDialog(this, "Price Updated Successfully!");
            txtServiceName.setText("");
            txtServiceNewPrice.setText("");
            populateTable();
        } catch (Exception ex) {
            Logger.getLogger(petGroomingServiceAdminUpdatePrice.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }//GEN-LAST:event_btnUpdateServicePriceActionPerformed

    private void tablePetGroomingServicesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tablePetGroomingServicesMouseClicked
        // TODO add your handling code here:
        DefaultTableModel model = (DefaultTableModel) tablePetGroomingServices.getModel();
        int selectedRowIndex = tablePetGroomingServices.getSelectedRow();
        String productName = (String) model.getValueAt(selectedRowIndex, 1);
        txtServiceName.setText(productName);
    }//GEN-LAST:event_tablePetGroomingServicesMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnUpdateServicePrice;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblServiceName;
    private javax.swing.JLabel lblServiceNewPrice;
    private javax.swing.JLabel lblUpdateFoodPrice;
    private javax.swing.JTable tablePetGroomingServices;
    private javax.swing.JTextField txtServiceName;
    private javax.swing.JTextField txtServiceNewPrice;
    // End of variables declaration//GEN-END:variables
}
