/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ui;
import model.databaseConnection;

/**
 *
 * @author babsybabu
 */
public class petShelterAdmin extends javax.swing.JPanel {

    /**
     * Creates new form petShelterAdmin
     */
    databaseConnection databaseConnection;

    public petShelterAdmin(databaseConnection databaseConnection) {
        initComponents();
        this.databaseConnection = databaseConnection;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        shelterAdminSplitPane = new javax.swing.JSplitPane();
        shelterAdminControlArea = new javax.swing.JPanel();
        btnAddPet = new javax.swing.JButton();
        btnViewAdoptedPets = new javax.swing.JButton();
        shelterAdminWorkArea = new javax.swing.JPanel();

        shelterAdminControlArea.setBackground(new java.awt.Color(102, 255, 102));

        btnAddPet.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        btnAddPet.setForeground(new java.awt.Color(255, 0, 0));
        btnAddPet.setText("Add pet");
        btnAddPet.setPreferredSize(new java.awt.Dimension(73, 30));
        btnAddPet.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddPetActionPerformed(evt);
            }
        });

        btnViewAdoptedPets.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        btnViewAdoptedPets.setForeground(new java.awt.Color(255, 0, 0));
        btnViewAdoptedPets.setText("View Adopted Pets");
        btnViewAdoptedPets.setPreferredSize(new java.awt.Dimension(137, 30));
        btnViewAdoptedPets.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewAdoptedPetsActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout shelterAdminControlAreaLayout = new javax.swing.GroupLayout(shelterAdminControlArea);
        shelterAdminControlArea.setLayout(shelterAdminControlAreaLayout);
        shelterAdminControlAreaLayout.setHorizontalGroup(
            shelterAdminControlAreaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(shelterAdminControlAreaLayout.createSequentialGroup()
                .addGroup(shelterAdminControlAreaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnViewAdoptedPets, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnAddPet, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        shelterAdminControlAreaLayout.setVerticalGroup(
            shelterAdminControlAreaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(shelterAdminControlAreaLayout.createSequentialGroup()
                .addGap(86, 86, 86)
                .addComponent(btnAddPet, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addComponent(btnViewAdoptedPets, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(255, Short.MAX_VALUE))
        );

        shelterAdminSplitPane.setLeftComponent(shelterAdminControlArea);

        shelterAdminWorkArea.setBackground(new java.awt.Color(0, 255, 255));

        javax.swing.GroupLayout shelterAdminWorkAreaLayout = new javax.swing.GroupLayout(shelterAdminWorkArea);
        shelterAdminWorkArea.setLayout(shelterAdminWorkAreaLayout);
        shelterAdminWorkAreaLayout.setHorizontalGroup(
            shelterAdminWorkAreaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 853, Short.MAX_VALUE)
        );
        shelterAdminWorkAreaLayout.setVerticalGroup(
            shelterAdminWorkAreaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 428, Short.MAX_VALUE)
        );

        shelterAdminSplitPane.setRightComponent(shelterAdminWorkArea);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(shelterAdminSplitPane)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(shelterAdminSplitPane)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnAddPetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddPetActionPerformed
        // TODO add your handling code here:
       petShelterAdminAddPets addPets = new petShelterAdminAddPets(databaseConnection);
       shelterAdminSplitPane.setRightComponent(addPets);
    }//GEN-LAST:event_btnAddPetActionPerformed

    private void btnViewAdoptedPetsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewAdoptedPetsActionPerformed
        // TODO add your handling code here:
        adoptedPetsJPanel addPets = new adoptedPetsJPanel(databaseConnection);
        shelterAdminSplitPane.setRightComponent(addPets);
    }//GEN-LAST:event_btnViewAdoptedPetsActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddPet;
    private javax.swing.JButton btnViewAdoptedPets;
    private javax.swing.JPanel shelterAdminControlArea;
    private javax.swing.JSplitPane shelterAdminSplitPane;
    private javax.swing.JPanel shelterAdminWorkArea;
    // End of variables declaration//GEN-END:variables
}
